version: "3.8"

services:
  postgres:
    image: postgres:latest
    env_file:
      - .envrc
    container_name: greenlight_new
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # host(changable):::::container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
